BulutProjesi/BulutProjesi/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import login_view,register_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',login_view, name="accounts"),
    path('',register_view, name="accounts"),
    path('exam/',include('exam.urls')),
    path('accounts/',include('accounts.urls')),
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BulutProjesi/accounts/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns = [
    path('login', login_view, name="login"),
    path('register', register_view, name="register"),
    path('logout', logout_view, name="logout"),
]

BulutProjesi/exam/urls.py
from django.urls import path
from .views import *

app_name='exam'

urlpatterns = [
    path('index', exam_index, name="index"),
    path('index2', exam_index2, name="index2"),
    path('<int:id>', exam_detail, name="detail"),
    path('<int:id>start', exam_start, name="start"),
    path('create', exam_create, name="create"),
    path('<int:id>/update', exam_update, name='update'),
    path('<int:id>/delete', exam_delete, name="delete"),
    path('<int:id>/assign_student', assign_student, name="assign_student"),
    path('<int:id>/assign_question', assign_question, name="assign_question"),
    path('question_create', question_create, name="create_question"),
]

BulutProjesi/accounts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, HttpResponse,redirect
from .form import LoginForm,RegisterForm
from django.contrib.auth import authenticate,login,logout



def login_view(request):
    form=LoginForm(request.POST or None)
    if form.is_valid():
        username=form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user=authenticate(username=username,password=password)
        login(request, user)
        return redirect("exam:index")
    return render(request, 'accounts/form.html', {"form":form})

def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user=form.save(commit=False)
        password=form.cleaned_data.get("password1")
        user.set_password(password)
        user.save()
        new_user=authenticate(username=user.username,password=password)

        login(request,new_user)
        return redirect("exam:index")
    return render(request, 'accounts/register.html', {"form": form})

def logout_view(request):
    logout(request)
    return redirect("accounts:login")

BulutProjesi/templates/accounts/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>LOGİN OTMT</title>
      <style>
          @import "https://use.fontawesome.com/releases/v5.5.0/css/all.css";
body{
  margin: 0;
  padding: 0;
  font-family: sans-serif;
  background:url("{% static "img/bglogin.jpg" %}")  no-repeat;
  background-size: cover;
}
.login-box{
  width: 280px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  color: white;
}
.login-box h1{
  float: left;
  font-size: 40px;
  border-bottom: 6px solid #4caf50;
  margin-bottom: 50px;
  padding: 13px 0;
}
.textbox{
  width: 100%;
  overflow: hidden;
  font-size: 20px;
  padding: 8px 0;
  margin: 8px 0;
  border-bottom: 1px solid #4caf50;
}
.textbox i{
  width: 26px;
  float: left;
  text-align: center;
}
.textbox input{
  border: none;
  outline: none;
  background: none;
  color: white;
  font-size: 18px;
  width: 80%;
  float: left;
  margin: 0 10px;
}
.btn{
  width: 100%;
  background: none;
  border: 2px solid #4caf50;
  color: white;
  padding: 5px;
  font-size: 18px;
  cursor: pointer;
  margin: 12px 0;
}

      </style>
  </head>
  <body>

<form method="post" class="login-box">
    {% csrf_token %}
  <h1>LOGIN</h1>
    {% if form.errors %}
        <div class="alert alert-primary textbox" style="border-bottom: 6px solid #4caf50;" role="alert">
      Kullanıcı Adı veya Parola Hatalı!
        </div>
   {% endif %}


  <div class="textbox">
    <i class="fas fa-user" ></i>
      {{ form.username}}
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    {{ form.password }}
  </div>

  <input type="submit" class="btn" value="Sign In">

<a href="{% url "accounts:register" %}">
   <input type="button" class="btn" value="Sign Up">
</a>


</form>
  </body>
</html>

BulutProjesi/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>REGİSTER</title>
      <style>
          @import "https://use.fontawesome.com/releases/v5.5.0/css/all.css";
body{
  margin: 0;
  padding: 0;
  font-family: sans-serif;
  background:url("{% static "img/bglogin.jpg" %}")  no-repeat;
  background-size: cover;
}
.login-box{
  width: 280px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  color: white;
}
.login-box h1{
  float: left;
  font-size: 40px;
  border-bottom: 6px solid #4caf50;
  margin-bottom: 50px;
  padding: 13px 0;
}
.textbox{
  width: 100%;
  overflow: hidden;
  font-size: 20px;
  padding: 8px 0;
  margin: 8px 0;
  border-bottom: 1px solid #4caf50;
}
.textbox i{
  width: 26px;
  float: left;
  text-align: center;
}
.textbox input{
  border: none;
  outline: none;
  background: none;
  color: white;
  font-size: 18px;
  width: 80%;
  float: left;
  margin: 0 10px;
}
.btn{
  width: 100%;
  background: none;
  border: 2px solid #4caf50;
  color: white;
  padding: 5px;
  font-size: 18px;
  cursor: pointer;
  margin: 12px 0;
}

      </style>
  </head>
  <body>

<form method="post" class="login-box">
    {% csrf_token %}
    <h1>REGISTER</h1>
    {% if form.errors %}
        <div class="alert alert-primary textbox" style="border-bottom: 6px solid #4caf50;" role="alert">
      Parolalar Eşleşmiyor!
        </div>
   {% endif %}


  <div class="textbox">
    <i class="fas fa-user" ></i>
      {{ form.username}}
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    {{ form.password1 }}
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    {{ form.password2 }}
  </div>

  <input type="submit" class="btn" value="Create Account">
  <a href="{% url "accounts:login" %}">
   <input type="button" class="btn" value="Sign In">
  </a>


</form>
  </body>
</html>