BulutProjesi/BulutProjesi/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import login_view,register_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',login_view, name="accounts"),
    path('',register_view, name="accounts"),
    path('exam/',include('exam.urls')),
    path('accounts/',include('accounts.urls')),
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BulutProjesi/accounts/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns = [
    path('login', login_view, name="login"),
    path('register', register_view, name="register"),
    path('logout', logout_view, name="logout"),
]

BulutProjesi/exam/urls.py
from django.urls import path
from .views import *

app_name='exam'

urlpatterns = [
    path('index', exam_index, name="index"),
    path('index2', exam_index2, name="index2"),
    path('<int:id>', exam_detail, name="detail"),
    path('<int:id>start', exam_start, name="start"),
    path('create', exam_create, name="create"),
    path('<int:id>/update', exam_update, name='update'),
    path('<int:id>/delete', exam_delete, name="delete"),
    path('<int:id>/assign_student', assign_student, name="assign_student"),
    path('<int:id>/assign_question', assign_question, name="assign_question"),
    path('question_create', question_create, name="create_question"),
]

BulutProjesi/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"  name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=yes">
    <title>{% block title %}bulut base{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <style>body{ background-color: black}</style>
</head>
<body>

    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}

    {% endblock %}

    <script src ="{% static "js/jQuery 3.5.1.js" %}"></script>
    <script src ="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>

BulutProjesi/templates/header.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark " style="background-color: black">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
        <h5 style="margin: 20px; font-weight: bold; color: #5cb85c" >{{ user.username }} {{ user.isStudent }} {{ user.role }}</h5>
      </li>
      <li class="nav-item active">
        <a href="{% url "exam:index" %}"class="btn btn-outline-success my-2 my-sm-0" style="margin: 10px; font-weight: bold">SINAVLARIM</a>
      </li>
      <li class="nav-item active">
        <a href="{% url "exam:index2" %}"class="btn btn-outline-success my-2 my-sm-0" style="margin: 10px; font-weight: bold">Bu kullancı tarafından Oluşturulmuş Sınavlar</a>
      </li>
      <li class="nav-item">
        <a href="{% url "exam:create" %}"class="btn btn-outline-success my-2 my-sm-0" style="margin: 10px; font-weight: bold">SINAV OLUŞTUR</a>
      </li>
      <li class="nav-item">
        <a href="{% url "accounts:logout" %}"class="btn btn-outline-success my-2 my-sm-0"  style="margin: 10px; font-weight: bold" >LOGOUT</a>
      </li>
    </ul>
    <form action={% url "exam:index" %} method="get" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" value="{{ request.GET.q }}" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" style="font-weight: bold" type="submit">Search</button>
    </form>

  </div>
</nav>

BulutProjesi/templates/messages.html
{% if messages %}

        {% for message in messages %}
          <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}

{% endif %}